server:
    port: 8002

spring:
    application:
        name: userprovider
    datasource:
        url: jdbc:mysql://localhost:3306/jpa002?serverTimezone=GMT%2B8
        username: root
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
#一定注意eureka与spring属于平级 注意格式
eureka:
    client:
        service-url:
            defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka

